# Generated by Django 2.0.2 on 2018-03-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GR', '0002_intervention_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='toggle',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
