# Generated by Django 2.0.2 on 2018-03-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GR', '0005_auto_20180301_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='style',
            field=models.IntegerField(default='1'),
        ),
    ]
